version: "3"

services:
  reverse-proxy:
    image: envoyproxy/envoy-alpine:v1.21.6
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./cert.pem:/etc/envoy/cert.pem   # 映射证书文件
      - ./key.pem:/etc/envoy/key.pem 

    ports:
      - "83:80"
      - "93:443"


  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'Origin works!' > index.html && python -m http.server 80"


  # origin:
  #   image: python:3.6.9-alpine
  #   volumes:
  #     - /home/lzy/pcap/origin/envoy:/pcap
  #     - /home/lzy/logs/envoy:/logs
  #     - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
  #     - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
  #     - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
  #   command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
