version: "3"

services:

  reverse-proxy:
    image: nginx:1.23-alpine3.17
    volumes:

      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
      - ./snakeoil.conf:/etc/nginx/snakeoil.conf
      - ./access.log:/var/log/nginx/access.log
      - ./error.log:/var/log/nginx/error.log

    ports:
      - "87:80"
      - "93:443"


  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'Origin works!' > index.html && python -m http.server 80"
